### ISSUE TITLE
Random background color

### ISSUE THREAD

**Issue by ghost** [washingtonstateuniversity/innovators.wsu.edu#2]
Looking for a way to have a set of background colors on body that is randomized in single-post.

**Comment by ghost** [comment]
![screen shot 2016-03-01 at 10 58 51 am](https://cloud.githubusercontent.com/assets/4007184/13438150/97b62510-df9c-11e5-977d-ab85ae220f1e.png)

**Comment by jeremyfelt** [comment]
@charlesjdillon You're in luck. :)

The Spine parent theme includes "random" body classes on every page load. https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/blob/d2d771f04a1be7cb053c3caa310a84e006ea2f53/functions.php#L613-L619

Since you have 6 colors, you would probably need to use the `ten` classes. You could target:

```
.single-post.ten1 {
  // random color 
}

.single-post.ten2 {
  // random color 
}

.single-post.ten3,
.single-post.ten7 {
  // random color 
}

.single-post.ten4,
.single-post.ten8 {
  // random color 
}

.single-post.ten5,
.single-post.ten9 {
  // random color 
}

.single-post.ten6,
.single-post.ten10 {
  // random color
}
```

It will be slightly un-random because of the 10 color slots rather than 6, but should do good enough.
